# Lapce IPC Server Configuration File

[server]
# Unix socket path for IPC communication
socket_path = "/var/run/lapce/ipc.sock"
# Maximum number of concurrent connections
max_connections = 2000
# Connection timeout in milliseconds
connection_timeout_ms = 5000
# Graceful shutdown timeout in milliseconds
shutdown_timeout_ms = 30000
# Enable message compression
enable_compression = true
# Compression level (1-22, higher = better compression but slower)
compression_level = 3

[performance]
# Size of the buffer pool for zero-allocation operations
buffer_pool_size = 1024
# Maximum message size in bytes
max_message_size = 1048576  # 1MB
# Number of worker threads (0 = number of CPU cores)
worker_threads = 0
# Internal queue size for backpressure control
queue_size = 10000
# Enable zero-copy optimizations
enable_zero_copy = true
# Batch size for processing multiple messages
batch_size = 100

[security]
# Enable authentication
enable_authentication = false
# Authentication token (set via environment variable LAPCE_AUTH_TOKEN in production)
auth_token = ""
# Enable encryption
enable_encryption = false
# IP allowlist (empty = allow all)
ip_allowlist = []
# Maximum request rate per client per second
max_request_rate = 1000
# Ban duration in seconds for rate limit violations
ban_duration_seconds = 300
# List of allowed RPC methods
allowed_methods = ["echo", "ping", "api", "stream", "health", "metrics", "completion", "ask", "edit", "chat"]
# Enable audit logging for security events
enable_audit_log = true
# Maximum failed authentication attempts before ban
max_failed_attempts = 5
# Enable request validation
enable_request_validation = true
# Maximum payload size for validation (bytes)
max_validation_size = 10485760

[monitoring]
# Enable metrics collection
enable_metrics = true
# Port for metrics endpoint (Prometheus format)
metrics_port = 9090
# Health check interval in milliseconds
health_check_interval_ms = 5000
# Enable Prometheus metrics export
enable_prometheus = true
# Enable web dashboard (not implemented yet)
enable_dashboard = false
# Dashboard port
dashboard_port = 8080

[logging]
# Log level (trace, debug, info, warn, error)
level = "info"
# Log format (pretty, json, compact)
format = "pretty"
# Output destination (stdout, stderr, file)
output = "stdout"
# Log file path (only used if output = "file")
file_path = "/var/log/lapce/ipc.log"
# Maximum log file size in MB
max_file_size_mb = 100
# Maximum number of log files to retain
max_files = 10
# Enable JSON structured logging
enable_json = false
