global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'semantic-search'
    static_configs:
      - targets: ['semantic-search:8080']
    metrics_path: /metrics
    scrape_interval: 5s
