#!/bin/bash
# Quick test script

echo "==================================="
echo "🚀 AI Chat Streaming Test"
echo "==================================="
echo ""
echo "✅ Backend running: PID 580171"
echo "✅ Control socket: /tmp/lapce_ai.sock.ctl"
echo "✅ Logs: /tmp/backend-final.log"
echo ""
echo "📋 Instructions:"
echo "1. Start Lapce: cd /home/verma/lapce && ./target/release/lapce"
echo "2. Open AI Chat panel (right sidebar)"
echo "3. Type: Hello!"
echo "4. Press Enter"
echo ""
echo "👀 Watch logs in another terminal:"
echo "   tail -f /tmp/backend-final.log | grep -E 'SERVER|Provider|HANDLER|STREAMING|JSON'"
echo ""
echo "Expected to see:"
echo "  - [SERVER] Accepted connection from client"
echo "  - [SERVER] Slot X: handshake complete"
echo "  - [STREAMING] Processing provider chat request"
echo "  - [Provider] Streaming chat request: model=gemini-1.5-flash"
echo ""
echo "🎯 If you see '[HANDLER] ✗ NO HANDLER' - backend needs rebuild!"
echo ""
