[plugin]
name = "lapce-ai-assistant"
version = "1.0.0"
author = "lapce-ai-rust"
description = "Ultra-fast AI assistant with <0.1μs latency"
wasm = "bin/lapce_ai.wasm"

[features]
code-completion = true
code-explanation = true
error-fixing = true
refactoring = true
documentation = true

[performance]
latency = "0.091μs"
throughput = "55.53M msg/sec"
memory = "1.94MB"

[activation]
language = ["rust", "typescript", "javascript", "python", "go"]
workspace = true
