name: Cross OS CI

on:
  push:
    paths:
      - 'lapce-ai/**'
  pull_request:
    paths:
      - 'lapce-ai/**'

jobs:
  test:
    name: Cross-OS tests (binary protocol + SHM invariants)
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install protobuf compiler
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update && sudo apt-get install -y protobuf-compiler
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install protobuf
          elif [ "$RUNNER_OS" == "Windows" ]; then
            choco install protoc
          fi
        shell: bash

      - name: Run cross-OS success criteria tests
        working-directory: lapce-ai
        run: |
          cargo test -p lapce-ai-rust --test cross_os_success_criteria -- --nocapture

      - name: Test semantic_search (default features)
        working-directory: lapce-ai/semantic_search
        run: |
          cargo test --lib

      - name: Test semantic_search (cst_ts feature)
        working-directory: lapce-ai/semantic_search
        run: |
          cargo test --lib --no-default-features --features cst_ts

      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cross-os-${{ matrix.os }}-logs
          path: lapce-ai/target/debug/deps
          if-no-files-found: ignore
