#:schema ../extra/schemas/color-theme.json

[color-theme]
name = "Impulsive Dark"

[ui]
font-family = ""
font-size = 13
header-height = 35
status-height = 25
tab-min-width = 100
activity-width = 50
scroll-width = 10
drop-shadow-width = 0

[color-theme.base]
# VS Code Dark Modern - Exact colors from theme
black = "#141414"
blue = "#569CD6"
cyan = "#4EC9B0"
green = "#6A9955"
grey = "#2B2B2B"
magenta = "#C586C0"
orange = "#CE9178"
purple = "#C586C0"
red = "#F48771"
white = "#E4E4E4"
yellow = "#DCDCAA"

# Primary = Sidebar, panels, status bar (#141414 = rgb(20,20,20))
primary-background = "#141414"
# Secondary = Editor background (#181818 = rgb(24,24,24))
secondary-background = "#181818"
current-background = "#2A2D2E"
text = "$white"
dim-text = "#E4E4E48C"

[color-theme.syntax]
"comment" = "$dim-text"
"constant" = "$yellow"
"type" = "$yellow"
"typeAlias" = "$yellow"
"number" = "$yellow"
"enum" = "$yellow"
"struct" = "$yellow"
"structure" = "$yellow"
"interface" = "$yellow"
"attribute" = "$yellow"
"constructor" = "$yellow"
"function" = "$blue"
"method" = "$blue"
"function.method" = "$blue"
"keyword" = "$purple"
"selfKeyword" = "$purple"
"field" = "$red"
"property" = "$red"
"enumMember" = "$red"
"enum-member" = "$red"
"string" = "$green"
"type.builtin" = "$cyan"
"builtinType" = "$cyan"
"escape" = "$cyan"
"string.escape" = "$cyan"
"embedded" = "$cyan"
"punctuation.delimiter" = "$yellow"
"text.title" = "$orange"
"text.uri" = "$cyan"
"text.reference" = "$yellow"
"variable" = "$red"
"variable.other.member" = "$red"
"tag" = "$blue"

"markup.heading" = "$red"
"markup.bold" = "$orange"
"markup.italic" = "$orange"
"markup.list" = "$orange"
"markup.link.url" = "$blue"
"markup.link.label" = "$purple"
"markup.link.text" = "$purple"

"bracket.color.1" = "$blue"
"bracket.color.2" = "$yellow"
"bracket.color.3" = "$purple"
"bracket.unpaired" = "$red"

[color-theme.ui]
"lapce.error" = "$red"
"lapce.warn" = "$yellow"
"lapce.dropdown_shadow" = "#000000"
"lapce.border" = "#E4E4E412"  # rgba(228, 228, 228, 0.07)
"lapce.scroll_bar" = "#E4E4E412"  # rgba(228, 228, 228, 0.07)

"lapce.button.primary.background" = "#0E639C"
"lapce.button.primary.foreground" = "#FFFFFF"

# Secondary buttons (like empty screen buttons)
"lapce.button.secondary.background" = "#3A3D41"
"lapce.button.secondary.foreground" = "#E4E4E4"
"lapce.button.secondary.hover" = "#45494E"

# Input fields and widgets
"lapce.input.background" = "#313131"
"lapce.input.foreground" = "#E4E4E4"
"lapce.input.border" = "#3C3C3C"
"lapce.input.placeholder" = "#8C8C8C"

# Dropdown and quick input
"lapce.dropdown.background" = "#313131"
"lapce.dropdown.foreground" = "#E4E4E4"
"lapce.dropdown.border" = "#3C3C3C"

# List/tree colors
"lapce.list.hover.background" = "#2A2D2E"
"lapce.list.focus.background" = "#04395E"
"lapce.list.focus.foreground" = "#E4E4E4"
"lapce.list.active.selection.background" = "#04395E"
"lapce.list.active.selection.foreground" = "#E4E4E4"
"lapce.list.inactive.selection.background" = "#37373D"
"lapce.list.inactive.selection.foreground" = "#E4E4E4"

# Sidebar section headers
"lapce.sidebar.section.header.background" = "$primary-background"
"lapce.sidebar.section.header.foreground" = "#E4E4E4"
"lapce.sidebar.section.header.border" = "#E4E4E412"

# tab
"lapce.tab.active.background" = "$primary-background"
"lapce.tab.active.foreground" = "#E4E4E4"
"lapce.tab.active.underline" = "#0078D4"

"lapce.tab.inactive.background" = "$primary-background"
"lapce.tab.inactive.foreground" = "#E4E4E48C"  # rgba(228, 228, 228, 0.55)
"lapce.tab.inactive.underline" = "#0078D477"

"lapce.tab.separator" = "#E4E4E412"  # rgba(228, 228, 228, 0.07)

"lapce.icon.active" = "#E4E4E4"
"lapce.icon.inactive" = "#E4E4E48C"

"lapce.remote.icon" = "$black"
"lapce.remote.local" = "#4078F2"
"lapce.remote.connected" = "#50A14F"
"lapce.remote.connecting" = "#C18401"
"lapce.remote.disconnected" = "#E45649"

"lapce.plugin.name" = "#DDDDDD"
"lapce.plugin.description" = "$text"
"lapce.plugin.author" = "#B0B0B0"

"editor.background" = "$secondary-background"  # rgb(24, 24, 24)
"editor.foreground" = "$text"
"editor.dim" = "$dim-text"
"editor.focus" = "#E4E4E4"
"editor.caret" = "#AEAFAD"
"editor.selection" = "#264F78"
"editor.current_line" = "#282828"
"editor.debug_break_line" = "#528abF37"
"editor.link" = "$blue"
"editor.visible_whitespace" = "#3C3C3C"
"editor.indent_guide" = "#404040"
"editor.drag_drop_background" = "#79c1fc55"
"editor.drag_drop_tab_background" = "#0b0e1455"
"editor.sticky_header_background" = "$secondary-background"

"inlay_hint.foreground" = "$text"
"inlay_hint.background" = "#528abF37"

"error_lens.error.foreground" = "$red"
"error_lens.error.background" = "#E06C7520"
"error_lens.warning.foreground" = "$yellow"
"error_lens.warning.background" = "#E5C07B20"
"error_lens.other.foreground" = "$dim-text"
"error_lens.other.background" = "#5C637020"

"completion_lens.foreground" = "$dim-text"

"source_control.added" = "#50A14FCC"
"source_control.removed" = "#FF5266CC"
"source_control.modified" = "#0184BCCC"

# Diff viewer colors
"diff.inserted.background" = "#50A14F20"  # Green with 12% opacity
"diff.inserted.foreground" = "#6A9955"    # Green text
"diff.removed.background" = "#FF526620"   # Red with 12% opacity
"diff.removed.foreground" = "#F48771"     # Red text

"tooltip.background" = "#252526"
"tooltip.foreground" = "$text"

"palette.background" = "#252526"  # Slightly lighter than sidebar
"palette.foreground" = "$text"
"palette.current.background" = "$current-background"
"palette.current.foreground" = "$text"

"completion.background" = "#252526"
"completion.current" = "$current-background"

"hover.background" = "#252526"

"activity.background" = "$primary-background"
"activity.current" = "$primary-background"

"debug.breakpoint" = "$red"
"debug.breakpoint.hover" = "#E06C7566"

"panel.background" = "$primary-background"  # rgb(20, 20, 20)
"panel.foreground" = "#E4E4E4EB"  # rgba(228,228,228,0.92)
"panel.foreground.dim" = "#E4E4E48C"  # rgba(228,228,228,0.55)
"panel.current.background" = "#2A2D2E"
"panel.current.foreground" = "$text"
"panel.current.foreground.dim" = "$dim-text"
"panel.hovered.background" = "#2A2D2E"
"panel.hovered.active.background" = "#2A2D2E"
"panel.hovered.foreground" = "$text"
"panel.hovered.foreground.dim" = "$dim-text"

"status.background" = "$primary-background"
"status.foreground" = "#E4E4E45E"  # rgba(228, 228, 228, 0.37)
"status.modal.normal.background" = "$blue"
"status.modal.normal.foreground" = "$black"
"status.modal.insert.background" = "$red"
"status.modal.insert.foreground" = "$black"
"status.modal.visual.background" = "$yellow"
"status.modal.visual.foreground" = "$black"
"status.modal.terminal.background" = "$purple"
"status.modal.terminal.foreground" = "$black"

"markdown.blockquote" = "#898989"

"terminal.cursor" = "$text"
"terminal.foreground" = "$text"
"terminal.background" = "$primary-background"
"terminal.white" = "$white"
"terminal.black" = "$black"
"terminal.red" = "$red"
"terminal.blue" = "$blue"
"terminal.green" = "$green"
"terminal.yellow" = "$yellow"
"terminal.cyan" = "$cyan"
"terminal.magenta" = "$magenta"
"terminal.bright_white" = "#C8CCD4"
"terminal.bright_red" = "$red"
"terminal.bright_blue" = "$blue"
"terminal.bright_green" = "$green"
"terminal.bright_yellow" = "$yellow"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_black" = "#545862"
