#:schema ../extra/schemas/icon-theme.json

[icon-theme]
name = "Lapce Codicons"

[icon-theme.ui]
"logo" = "lapce_logo.svg"
"menu" = "menu.svg"
"link" = "link.svg"
"error" = "error.svg"
"add" = "add.svg"
"close" = "close.svg"
"remote" = "remote.svg"
"unsaved" = "circle-filled.svg"
"warning" = "warning.svg"
"problem" = "problem.svg"
"debug" = "debug.svg"
"debug_breakpoint" = "circle-filled.svg"
"debug_alt" = "debug-alt.svg"
"debug_small" = "debug-alt-small.svg"
"debug_restart" = "debug-restart.svg"
"debug_continue" = "debug-continue.svg"
"debug_step_over" = "debug-step-over.svg"
"debug_step_into" = "debug-step-into.svg"
"debug_step_out" = "debug-step-out.svg"
"debug_pause" = "debug-pause.svg"
"debug_stop" = "debug-stop.svg"
"debug_console" = "debug-console.svg"
"debug_disconnect" = "debug-disconnect.svg"
"start" = "debug-start.svg"
"run_errors" = "run-errors.svg"
"settings" = "settings-gear.svg"
"terminal" = "terminal.svg"
"lightbulb" = "lightbulb.svg"
"extensions" = "extensions.svg"
"keyboard" = "keyboard.svg"
"breadcrumb_separator" = "chevron-right.svg"
"symbol_color" = "symbol-color.svg"
"type_hierarchy" = "type-hierarchy.svg"

"window.close" = "chrome-close.svg"
"window.restore" = "chrome-restore.svg"
"window.maximize" = "chrome-maximize.svg"
"window.minimize" = "chrome-minimize.svg"

"file" = "file.svg"
"file_explorer" = "files.svg"
"file_picker_up" = "arrow-up.svg"

"image_loading" = "refresh.svg"
"image_error" = "error.svg"

"scm.icon" = "source-control.svg"
"scm.diff.modified" = "diff-modified.svg"
"scm.diff.added" = "diff-added.svg"
"scm.diff.removed" = "diff-removed.svg"
"scm.diff.renamed" = "diff-renamed.svg"
"scm.change.add" = "add.svg"
"scm.change.remove" = "remove.svg"

"palette.menu" = "chevron-down.svg"

"fold" = "fold.svg"
"fold.up" = "fold-up.svg"
"fold.down" = "fold-down.svg"

"dropdown.arrow" = "chevron-down.svg"

"panel.fold-down" = "chevron-down.svg"
"panel.fold-up" = "chevron-right.svg"

"location.forward" = "arrow-right.svg"
"location.backward" = "arrow-left.svg"

"item.opened" = "chevron-down.svg"
"item.closed" = "chevron-right.svg"

"directory.closed" = "folder.svg"
"directory.opened" = "folder-opened.svg"

"panel.restore" = "chevron-down.svg"
"panel.maximise" = "chevron-right.svg"

"split.horizontal" = "split-horizontal.svg"

"tab.previous" = "chevron-left.svg"
"tab.next" = "chevron-right.svg"

"sidebar.left.on" = "layout-sidebar-left.svg"
"sidebar.left.off" = "layout-sidebar-left-off.svg"
"sidebar.right.on" = "layout-sidebar-right.svg"
"sidebar.right.off" = "layout-sidebar-right-off.svg"

"layout.panel.on" = "layout-panel.svg"
"layout.panel.off" = "layout-panel-off.svg"

"search.icon" = "search.svg"
"search.clear" = "close.svg"
"search.forward" = "arrow-down.svg"
"search.backward" = "arrow-up.svg"
"search.case_sensitive" = "case-sensitive.svg"
"search.whole_word" = "whole-word.svg"
"search.regex" = "regex.svg"
"search.replace" = "replace.svg"
"search.replace_all" = "replace-all.svg"

"document_symbol" = "symbol-class.svg"
"references" = "references.svg"
"implementation" = "combine.svg"
"symbol_kind.array" = "symbol-array.svg"
"symbol_kind.boolean" = "symbol-boolean.svg"
"symbol_kind.class" = "symbol-class.svg"
"symbol_kind.constant" = "symbol-constant.svg"
"symbol_kind.enum_member" = "symbol-enum-member.svg"
"symbol_kind.enum" = "symbol-enum.svg"
"symbol_kind.event" = "symbol-event.svg"
"symbol_kind.field" = "symbol-field.svg"
"symbol_kind.file" = "symbol-file.svg"
"symbol_kind.function" = "symbol-method.svg"
"symbol_kind.interface" = "symbol-interface.svg"
"symbol_kind.key" = "symbol-key.svg"
"symbol_kind.method" = "symbol-method.svg"
"symbol_kind.namespace" = "symbol-namespace.svg"
"symbol_kind.number" = "symbol-numeric.svg"
"symbol_kind.object" = "symbol-namespace.svg"
"symbol_kind.operator" = "symbol-operator.svg"
"symbol_kind.property" = "symbol-property.svg"
"symbol_kind.string" = "symbol-string.svg"
"symbol_kind.struct" = "symbol-structure.svg"
"symbol_kind.type_parameter" = "symbol-parameter.svg"
"symbol_kind.variable" = "symbol-variable.svg"

"completion_item_kind.class" = "symbol-class.svg"
"completion_item_kind.constant" = "symbol-constant.svg"
"completion_item_kind.enum_member" = "symbol-enum-member.svg"
"completion_item_kind.enum" = "symbol-enum.svg"
"completion_item_kind.field" = "symbol-field.svg"
"completion_item_kind.function" = "symbol-method.svg"
"completion_item_kind.interface" = "symbol-interface.svg"
"completion_item_kind.keyword" = "symbol-keyword.svg"
"completion_item_kind.method" = "symbol-method.svg"
"completion_item_kind.module" = "symbol-namespace.svg"
"completion_item_kind.property" = "symbol-property.svg"
"completion_item_kind.snippet" = "symbol-snippet.svg"
"completion_item_kind.string" = "symbol-string.svg"
"completion_item_kind.struct" = "symbol-structure.svg"
"completion_item_kind.variable" = "symbol-variable.svg"

[icon-theme.foldername]
# Folder-specific icons - ONLY using icons that exist!
"node_modules" = "folder-node-modules.svg"
".github" = "folder-github.svg"
".gitlab" = "folder-gitlab.svg"
".vscode" = "folder-vscode.svg"
"target" = "folder-target.svg"
"build" = "folder-build.svg"

# Source code folders
"src" = "folder-src.svg"

# Web/Frontend folders
"assets" = "folder-assets.svg"
"images" = "folder-images.svg"
"img" = "folder-images.svg"
"layouts" = "folder-layout.svg"
"layout" = "folder-layout.svg"
"styles" = "folder-sass.svg"
"css" = "folder-sass.svg"
"sass" = "folder-sass.svg"
"scss" = "folder-sass.svg"
"fonts" = "folder-fonts.svg"
"hooks" = "folder-hooks.svg"
"effects" = "folder-effects.svg"
"providers" = "folder-providers.svg"
"reducer" = "folder-reducer.svg"
"reducers" = "folder-reducer.svg"
"selector" = "folder-selector.svg"
"selectors" = "folder-selector.svg"
"pipes" = "folder-pipes.svg"
"interceptors" = "folder-interceptors.svg"
"interfaces" = "folder-interfaces.svg"
"router" = "folder-router.svg"
"routes" = "folder-router.svg"

# Framework specific
".angular" = "folder-angular.svg"
"angular" = "folder-angular.svg"
".gradle" = "folder-gradle.svg"
"react" = "folder-react.svg"

# Config/Settings
"config" = "folder-config.svg"
"configs" = "folder-config.svg"
".config" = "folder-config.svg"
"constants" = "folder-constants.svg"

# Testing
"cypress" = "folder-cypress.svg"

# Documentation
"docs" = "folder-documents.svg"
"doc" = "folder-documents.svg"
"documentation" = "folder-documents.svg"
"documents" = "folder-documents.svg"

# Docker/DevOps
"docker" = "folder-docker.svg"
".docker" = "folder-docker.svg"
"nginx" = "folder-nginx.svg"

# Database/Data
"db" = "folder-database.svg"
"database" = "folder-database.svg"
"mongo" = "folder-mongo.svg"
"mongodb" = "folder-mongo.svg"
"prisma" = "folder-prisma.svg"
"drizzle" = "folder-drizzle.svg"
"supabase" = "folder-supabase.svg"
"graphql" = "folder-graphql.svg"

# Utils/Helpers
"utils" = "folder-utils.svg"
"util" = "folder-utils.svg"
"helpers" = "folder-helpers.svg"
"helper" = "folder-helpers.svg"
"core" = "folder-core.svg"
"shared" = "folder-shared.svg"
"common" = "folder-shared.svg"
"modules" = "folder-modules.svg"
"context" = "folder-context.svg"
"facade" = "folder-facade.svg"

# Server/API
"middleware" = "folder-middleware.svg"
"models" = "folder-models.svg"
"services" = "folder-services.svg"
"actions" = "folder-actions.svg"

# Mobile
"android" = "folder-android.svg"
"ios" = "folder-ios.svg"
"expo" = "folder-expo.svg"
"tauri" = "folder-tauri.svg"

# Cloud/Tools
"aws" = "folder-aws.svg"
"azure" = "folder-azure.svg"
"firebase" = "folder-firebase.svg"
"vercel" = "folder-vercel.svg"
"tina" = "folder-tina.svg"
"bruno" = "folder-bruno.svg"
"cursor" = "folder-cursor.svg"

# Other
"js" = "folder-js.svg"
"javascript" = "folder-js.svg"
"mail" = "folder-mail.svg"
"i18n" = "folder-i18n.svg"
"app" = "folder-app.svg"

[icon-theme.filename]
# Special filename icons
"Cargo.toml" = "rust.svg"
"Cargo.lock" = "lock.svg"
"package.json" = "node.svg"
"package-lock.json" = "npm.svg"
"yarn.lock" = "yarn.svg"
"pnpm-lock.yaml" = "pnpm.svg"
"bun.lockb" = "bun.svg"
"tsconfig.json" = "tsconfig.svg"
"jsconfig.json" = "js.svg"
"webpack.config.js" = "webpack.svg"
"vite.config.js" = "vite.svg"
"vite.config.ts" = "vite.svg"
"vitest.config.js" = "vitest.svg"
"vitest.config.ts" = "vitest.svg"
"jest.config.js" = "jest.svg"
"jest.config.ts" = "jest.svg"
"cypress.json" = "cypress.svg"
"next.config.js" = "next.svg"
"next.config.mjs" = "next.svg"
"nuxt.config.js" = "nuxt.svg"
"nuxt.config.ts" = "nuxt.svg"
"astro.config.mjs" = "astro.svg"
"svelte.config.js" = "svelte.svg"
"tailwind.config.js" = "tailwind.svg"
"tailwind.config.ts" = "tailwind.svg"
"postcss.config.js" = "postcss.svg"
"gatsby-config.js" = "gatsby.svg"
"remix.config.js" = "gear.svg"
"Makefile" = "gear.svg"
"CMakeLists.txt" = "cmake.svg"
"Dockerfile" = "docker.svg"
"docker-compose.yml" = "docker.svg"
"docker-compose.yaml" = "docker.svg"
".gitignore" = "git.svg"
".dockerignore" = "docker.svg"
".editorconfig" = "editorconfig.svg"
".prettierrc" = "prettier.svg"
".prettierrc.json" = "prettier.svg"
".eslintrc" = "eslint.svg"
".eslintrc.json" = "eslint.svg"
".eslintrc.js" = "eslint.svg"
"eslint.config.js" = "eslint.svg"
".stylelintrc" = "stylelint.svg"
"biome.json" = "biome.svg"
"deno.json" = "deno.svg"
"README.md" = "markdown.svg"
"LICENSE" = "license.svg"
"CHANGELOG.md" = "markdown.svg"
".env" = "gear.svg"
".env.local" = "gear.svg"
".env.development" = "gear.svg"
".env.production" = "gear.svg"
"go.mod" = "go.svg"
"go.sum" = "go.svg"
"Gemfile" = "ruby.svg"
"Gemfile.lock" = "ruby.svg"
"Pipfile" = "python.svg"
"requirements.txt" = "python.svg"
"setup.py" = "python.svg"
"pyproject.toml" = "python.svg"
"pom.xml" = "java.svg"
"build.gradle" = "gradle.svg"
"build.gradle.kts" = "gradle.svg"
"settings.gradle" = "gradle.svg"
"pubspec.yaml" = "dart.svg"
"composer.json" = "php.svg"
"prisma.schema" = "prisma.svg"

[icon-theme.extension]
# Programming languages - Comprehensive mappings!
"rs" = "rust.svg"
"py" = "python.svg"
"js" = "js.svg"
"mjs" = "js.svg"
"cjs" = "js.svg"
"ts" = "ts.svg"
"mts" = "ts.svg"
"cts" = "ts.svg"
"jsx" = "react.svg"
"tsx" = "react-ts.svg"
"c" = "c.svg"
"cpp" = "cplus.svg"
"cc" = "cplus.svg"
"cxx" = "cplus.svg"
"h" = "h.svg"
"hpp" = "h.svg"
"hxx" = "h.svg"
"cs" = "csharp.svg"
"go" = "go.svg"
"java" = "java.svg"
"kt" = "kotlin.svg"
"kts" = "kotlin.svg"
"rb" = "ruby.svg"
"php" = "php.svg"
"sh" = "shell.svg"
"bash" = "shell.svg"
"zsh" = "shell.svg"
"fish" = "shell.svg"
"swift" = "swift.svg"
"dart" = "dart.svg"
"scala" = "scala.svg"
"sc" = "scala.svg"
"clj" = "clojure.svg"
"cljs" = "clojure.svg"
"cljc" = "clojure.svg"
"edn" = "clojure.svg"
"ex" = "elixir.svg"
"exs" = "elixir.svg"
"erl" = "erlang.svg"
"hrl" = "erlang.svg"
"hs" = "haskell.svg"
"lhs" = "haskell.svg"
"lua" = "lua.svg"
"pl" = "perl.svg"
"pm" = "perl.svg"
"r" = "r.svg"
"R" = "r.svg"
"jl" = "julia.svg"
"nim" = "nim.svg"
"nimble" = "nim.svg"
"cr" = "crystal.svg"
"zig" = "zig.svg"
"v" = "v.svg"
"sol" = "solidity.svg"
"f90" = "fortran.svg"
"f95" = "fortran.svg"
"f03" = "fortran.svg"
"for" = "fortran.svg"
"ml" = "ocaml.svg"
"mli" = "ocaml.svg"
"fs" = "fsharp.svg"
"fsx" = "fsharp.svg"
"fsi" = "fsharp.svg"
"res" = "rescript.svg"
"resi" = "rescript-interface.svg"

# Web/Markup/Styles
"html" = "document.svg"
"htm" = "document.svg"
"css" = "sass.svg"
"scss" = "sass.svg"
"sass" = "sass.svg"
"less" = "sass.svg"
"styl" = "stylus.svg"
"vue" = "vue.svg"
"svelte" = "svelte.svg"
"astro" = "astro.svg"
"xml" = "xml.svg"
"svg" = "svg.svg"
"pug" = "pug.svg"
"jade" = "pug.svg"
"haml" = "haml.svg"
"twig" = "twig.svg"
"liquid" = "liquid.svg"
"ejs" = "document.svg"
"hbs" = "document.svg"
"handlebars" = "document.svg"
"njk" = "nunjucks.svg"
"nunjucks" = "nunjucks.svg"

# Data/Config formats
"json" = "js.svg"
"jsonc" = "js.svg"
"json5" = "js.svg"
"toml" = "gear.svg"
"yaml" = "yaml.svg"
"yml" = "yaml.svg"
"ini" = "gear.svg"
"cfg" = "gear.svg"
"conf" = "gear.svg"
"env" = "gear.svg"
"properties" = "gear.svg"

# Documentation
"md" = "markdown.svg"
"mdx" = "mdx.svg"
"txt" = "text.svg"
"rst" = "text.svg"
"adoc" = "text.svg"
"tex" = "tex.svg"
"latex" = "tex.svg"

# Archives
"zip" = "file-zip.svg"
"tar" = "file-zip.svg"
"gz" = "file-zip.svg"

# Media files
"png" = "file-media.svg"
"jpg" = "file-media.svg"
"jpeg" = "file-media.svg"
"gif" = "file-media.svg"
"mp3" = "file-media.svg"
"mp4" = "file-media.svg"

# Documents
"pdf" = "file-pdf.svg"

# Binary/Compiled
"exe" = "file-binary.svg"
"so" = "file-binary.svg"
"wasm" = "file-binary.svg"
