#:schema ../extra/schemas/color-theme.json

[color-theme]
name = "Lapce Light High Contrast"
high-contrast = true

[ui]
font-family = ""
font-size = 13
header-height = 35
status-height = 25
tab-min-width = 100
activity-width = 50
scroll-width = 10
drop-shadow-width = 0

[color-theme.base]
# VSCode Light High Contrast colors - maximum contrast for accessibility
black = "#000000"
blue = "#0F4A85"
cyan = "#0184BC"
green = "#096D48"
grey = "#E5E5E5"
magenta = "#811F3F"
orange = "#D19A66"
purple = "#0F4A85"
red = "#B5200D"
white = "#FFFFFF"
yellow = "#895503"

primary-background = "#FFFFFF"
secondary-background = "#F8F8F8"
current-background = "#E8E8E8"
text = "#292929"
dim-text = "#515151"

[color-theme.syntax]
"comment" = "$dim-text"
"constant" = "$blue"
"type" = "$blue"
"typeAlias" = "$blue"
"number" = "$green"
"enum" = "$blue"
"struct" = "$blue"
"structure" = "$blue"
"interface" = "$blue"
"attribute" = "#264F78"
"constructor" = "$blue"

"function" = "$blue"
"method" = "$blue"
"function.method" = "$blue"

"keyword" = "$blue"
"selfKeyword" = "$blue"

"field" = "#0451A5"
"property" = "#0451A5"
"enumMember" = "$green"
"enum-member" = "$green"

"string" = "$blue"
"string.escape" = "$cyan"

"type.builtin" = "$blue"
"builtinType" = "$blue"
"escape" = "$cyan"
"embedded" = "$text"

"punctuation.delimiter" = "$black"
"text.title" = "$blue"
"text.uri" = "$cyan"
"text.reference" = "$blue"
"variable" = "#0451A5"
"variable.other.member" = "#0451A5"
"tag" = "$blue"

"markup.heading" = "$blue"
"markup.bold" = "#000080"
"markup.italic" = "$black"
"markup.list" = "$blue"
"markup.link.url" = "$blue"
"markup.link.label" = "$purple"
"markup.link.text" = "$purple"

"bracket.color.1" = "$blue"
"bracket.color.2" = "$green"
"bracket.color.3" = "$purple"
"bracket.unpaired" = "$red"

[color-theme.ui]
"lapce.error" = "$red"
"lapce.warn" = "$yellow"
"lapce.dropdown_shadow" = "#B4B4B4"
"lapce.border" = "$black"
"lapce.scroll_bar" = "$black"

"lapce.button.primary.background" = "#005FB8"
"lapce.button.primary.foreground" = "$white"

# tab
"lapce.tab.active.background" = "$primary-background"
"lapce.tab.active.foreground" = "$black"
"lapce.tab.active.underline" = "$black"

"lapce.tab.inactive.background" = "$secondary-background"
"lapce.tab.inactive.foreground" = "$dim-text"
"lapce.tab.inactive.underline" = "$dim-text"

"lapce.tab.separator" = "$black"

"lapce.icon.active" = "$black"
"lapce.icon.inactive" = "$dim-text"

"lapce.remote.icon" = "$white"
"lapce.remote.local" = "#4078F2"
"lapce.remote.connected" = "#50A14F"
"lapce.remote.connecting" = "#C18401"
"lapce.remote.disconnected" = "#E45649"

"lapce.plugin.name" = "$black"
"lapce.plugin.description" = "$text"
"lapce.plugin.author" = "$dim-text"

"editor.background" = "$primary-background"
"editor.foreground" = "$text"
"editor.dim" = "$dim-text"
"editor.focus" = "$black"
"editor.caret" = "$black"
"editor.selection" = "#E5EBF1"
"editor.current_line" = "#F2F2F2"
"editor.debug_break_line" = "#528bFF55"
"editor.link" = "$blue"
"editor.visible_whitespace" = "$grey"
"editor.indent_guide" = "$black"
"editor.drag_drop_background" = "#79c1fc33"
"editor.drag_drop_tab_background" = "#0b0e1433"
"editor.sticky_header_background" = "$primary-background"

"inlay_hint.foreground" = "$text"
"inlay_hint.background" = "#528bFF55"

"error_lens.error.foreground" = "$red"
"error_lens.error.background" = "#B5200D20"
"error_lens.warning.foreground" = "$yellow"
"error_lens.warning.background" = "#89550320"
"error_lens.other.foreground" = "$dim-text"
"error_lens.other.background" = "#51515120"

"completion_lens.foreground" = "$dim-text"

"source_control.added" = "#096D48CC"
"source_control.removed" = "#B5200DCC"
"source_control.modified" = "#0184BCCC"

"tooltip.background" = "$primary-background"
"tooltip.foreground" = "$text"

"palette.background" = "$secondary-background"
"palette.foreground" = "$text"
"palette.current.background" = "$current-background"
"palette.current.foreground" = "$text"

"completion.background" = "$secondary-background"
"completion.current" = "$current-background"

"hover.background" = "$secondary-background"

"activity.background" = "$secondary-background"
"activity.current" = "$primary-background"

"debug.breakpoint" = "$red"
"debug.breakpoint.hover" = "#B5200D66"

"panel.background" = "$secondary-background"
"panel.foreground" = "$text"
"panel.foreground.dim" = "$dim-text"
"panel.current.background" = "$current-background"
"panel.current.foreground" = "$text"
"panel.current.foreground.dim" = "$dim-text"
"panel.hovered.background" = "#E8E8E8"
"panel.hovered.active.background" = "$dim-text"
"panel.hovered.foreground" = "$text"
"panel.hovered.foreground.dim" = "$dim-text"

"status.background" = "$secondary-background"
"status.foreground" = "$text"
"status.modal.normal.background" = "$blue"
"status.modal.normal.foreground" = "$white"
"status.modal.insert.background" = "$red"
"status.modal.insert.foreground" = "$white"
"status.modal.visual.background" = "$yellow"
"status.modal.visual.foreground" = "$white"
"status.modal.terminal.background" = "$purple"
"status.modal.terminal.foreground" = "$white"

"markdown.blockquote" = "#515151"

"terminal.cursor" = "$text"
"terminal.foreground" = "$text"
"terminal.background" = "$primary-background"
"terminal.white" = "$white"
"terminal.black" = "$black"
"terminal.red" = "$red"
"terminal.blue" = "$blue"
"terminal.green" = "$green"
"terminal.yellow" = "$yellow"
"terminal.cyan" = "$cyan"
"terminal.magenta" = "$magenta"
"terminal.bright_white" = "$white"
"terminal.bright_red" = "$red"
"terminal.bright_blue" = "$blue"
"terminal.bright_green" = "$green"
"terminal.bright_yellow" = "$yellow"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_black" = "$dim-text"
