# COMPLETE 62 LANGUAGES FOR LAPCE TREE-SITTER

[dependencies]
tree-sitter = "0.24"
streaming-iterator = "0.1"
tree-sitter-highlight = "0.24"
once_cell = "1.18"
regex = "1.9"
rayon = "1.10"
anyhow = "1.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dashmap = "5.5"
parking_lot = "0.12"
lazy_static = "1.4"
bytes = "1.5"
tokio = { version = "1.35", features = ["fs", "rt", "rt-multi-thread", "macros"] }
moka = { version = "0.12", features = ["sync"] }
arc-swap = "1.7"
ignore = "0.4"
sha2 = "0.10"

# === ORIGINAL 20 LANGUAGES (Crates.io) ===
tree-sitter-rust = "0.24.0"
tree-sitter-javascript = "0.25.0"
tree-sitter-typescript = "0.23.2"
tree-sitter-python = "0.25.0"
tree-sitter-go = "0.25.0"
tree-sitter-java = "0.23.5"
tree-sitter-c = "0.24.1"
tree-sitter-cpp = "0.23.4"
tree-sitter-c-sharp = "0.23.1"
tree-sitter-ruby = "0.23.1"
tree-sitter-php = "0.24.2"
tree-sitter-lua = "0.2.0"
tree-sitter-bash = "0.25.0"
tree-sitter-css = "0.23.2"
tree-sitter-json = "0.24.8"
tree-sitter-swift = "0.7.1"
tree-sitter-scala = "0.24.0"
tree-sitter-elixir = "0.3.4"
tree-sitter-html = "0.23.2"
tree-sitter-elm = "5.8.0"

# === ADDITIONAL 21 LANGUAGES (Crates.io) ===
tree-sitter-toml = "0.20.0"
tree-sitter-ocaml = "0.24"
tree-sitter-nix = "0.3.0"
tree-sitter-latex = "0.1.0"
tree-sitter-make = "1.1.1"
tree-sitter-cmake = "0.7.1"
tree-sitter-verilog = "1.0.3"
tree-sitter-erlang = "0.14.0"
tree-sitter-d = "0.8.2"
tree-sitter-dockerfile = "0.2.0"
tree-sitter-pascal = "0.10.0"
tree-sitter-commonlisp = "0.4.1"
tree-sitter-prisma = "0.1.1"
tree-sitter-hlsl = "0.1.2"
tree-sitter-objc = "3.0.1"
tree-sitter-cobol = "0.1.0"
tree-sitter-groovy = "0.1.1"
tree-sitter-hcl = "1.1.0"
tree-sitter-solidity = "1.2.13"
tree-sitter-fsharp = "0.1.0"
tree-sitter-powershell = "0.25.9"
tree-sitter-systemverilog = "0.2.1"
tree-sitter-embedded-template = "0.23.2"

# === NEW 21 LANGUAGES (Path Dependencies) ===
tree-sitter-kotlin = { path = "external-grammars/tree-sitter-kotlin" }
tree-sitter-yaml = { path = "external-grammars/tree-sitter-yaml" }
tree-sitter-r = { path = "external-grammars/tree-sitter-r" }
tree-sitter-matlab = { path = "external-grammars/tree-sitter-matlab" }
tree-sitter-perl = { path = "external-grammars/tree-sitter-perl" }
tree-sitter-dart = { path = "external-grammars/tree-sitter-dart" }
tree-sitter-julia = { path = "external-grammars/tree-sitter-julia" }
tree-sitter-haskell = { path = "external-grammars/tree-sitter-haskell" }
tree-sitter-graphql = { path = "external-grammars/tree-sitter-graphql" }
tree-sitter-sql = { path = "external-grammars/tree-sitter-sql" }
tree-sitter-zig = { path = "external-grammars/tree-sitter-zig" }
tree-sitter-vim = { path = "external-grammars/tree-sitter-vim" }
tree-sitter-abap = { path = "external-grammars/tree-sitter-abap" }
tree-sitter-nim = { path = "external-grammars/tree-sitter-nim" }
tree-sitter-clojure = { path = "external-grammars/tree-sitter-clojure" }
tree-sitter-crystal = { path = "external-grammars/tree-sitter-crystal" }
tree-sitter-fortran = { path = "external-grammars/tree-sitter-fortran" }
tree-sitter-vhdl = { path = "external-grammars/tree-sitter-vhdl" }
tree-sitter-racket = { path = "external-grammars/tree-sitter-racket" }
tree-sitter-ada = { path = "external-grammars/tree-sitter-ada" }
tree-sitter-prolog = { path = "external-grammars/tree-sitter-prolog" }

# TOTAL: 62 LANGUAGES
