name: Semantic Search Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'semantic_search/**'
      - '.github/workflows/test.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'semantic_search/**'

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test Semantic Search
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
    
    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Cache target directory
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-target-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Check formatting
      run: |
        cd semantic_search
        cargo fmt -- --check
    
    - name: Run clippy
      run: |
        cd semantic_search
        cargo clippy -- -D warnings
    
    - name: Build
      run: |
        cd semantic_search
        cargo build --release --no-default-features
    
    - name: Run tests
      run: |
        cd semantic_search
        cargo test --no-default-features -- --nocapture
    
    - name: Run integration test
      run: |
        cd semantic_search
        cargo test --test integration_test --no-default-features
    
    - name: Check memory usage
      run: |
        cd semantic_search
        # Run a simple memory benchmark
        timeout 30s cargo run --example simple --release --no-default-features || true
